version: "3.5"

services:
  lumen-app:
    container_name: lumen-api
    build:
      args:
        user: user
        uid: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./code:/var/www/api

  lumen-db:
    container_name: lumen-mysql
    image: mysql:8.0
    healthcheck:
      test: nc -z 3306
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=default
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=myuser
    ports:
      - "3309:3306"

  lumen-server:
      image: nginx:alpine
      container_name: lumen-nginx
      restart: unless-stopped
      depends_on:
        - lumen-db
        - lumen-app
      ports:
        - "8800:80"
      volumes:
        - ./web.conf:/etc/nginx/conf.d/default.conf

